Add controllers
AleksandrTimofeev1987/java-shareit pull request #3
Opened 2022-11-20 10:43 UTC by AleksandrTimofeev1987

2022-11-21 18:31 UTC, Fleaman777 requested changes

2022-11-21 18:31 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/exception/model/item/MissingAvailabilityException.java
> +package ru.practicum.shareit.exception.model.item;
эксепшены можно поместить в отдельный exception пакет

2022-11-21 18:31 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        log.debug("Request to update item with ID - {} is received from user with ID - {}.", itemId, userId);
не совсем корректный может быть лог, т.к. этот метод может использоваться не только контроллером, который принял запрос, но другими сервисами

2022-11-21 19:01 UTC, AleksandrTimofeev1987 commented on src/main/java/ru/practicum/shareit/exception/model/item/MissingAvailabilityException.java
> +package ru.practicum.shareit.exception.model.item;
Так у меня и так в отдельном пакете ru.practicum.shareit.exception. Или ты что-то другое имеешь ввиду?

2022-11-21 19:06 UTC, AleksandrTimofeev1987 commented on src/main/java/ru/practicum/shareit/user/validation/UserValidator.java
> +        if (user.getEmail() == null || user.getEmail().equals("")) {
Спасибо за подсказку. Почитал документацию, посмотрел методы - очень крутая библиотека! Начну, пожалуй прямо сейчас.)
Вообще хотел валидацию через javax.validation.constraints сделать в модели, там как раз и @NotBlank и @Email есть, да и куча других проверок, но так как на вход приходят DTOшки зачастую с пустыми параметрами, не понял как можно все это дело вместе скрутить, чтобы работало. В итоге написал валидаторы. Со StringUtils точно все красивее станет)

2022-11-22 16:45 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/exception/model/item/MissingAvailabilityException.java
> +package ru.practicum.shareit.exception.model.item;
а да, все верно у тебя, теперь увидел, что эксепшены в своем пакете)

как еще один вариант, который часто встрчается, ErrorHandler делать вместе с контроллерами, в одном пакете, а эксепшены просто в пекедже exception, без каких либо других вложенны пакетов

но твой вариант тоже неплохо выглядит, можешь не менять)

2022-11-22 16:53 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/validation/UserValidator.java
> +        if (user.getEmail() == null || user.getEmail().equals("")) {
правильно, чем раньше, тем лучше))

так а там же, обычно, аннтоации вешаются над полями, в DTO классах, которые точно нужно валидировать, а все остальные, которые не помечены никакими аннотациями, могут иметь, что угодно, в том числе ничего)

с отдельно вынесенной валидацией - хороший вариант, прозранчый и легко тестируемый

2022-11-25 11:42 UTC, merged